<?php 
	session_start();
	// Authentication Check
	if(!isset($_SESSION['id'])){
		header('location:../../../login.php');
		exit;
	}
 ?>
<?php
	header('Content-Type: application/json');
	$data = array(
		array("total_transection"=>5696,"branch_full_name"=>"Aganagar Branch"),
		array("total_transection"=>7482,"branch_full_name"=>"Akhaura Branch"),
		array("total_transection"=>6804,"branch_full_name"=>"Alankar More Branch"),
		array("total_transection"=>9731,"branch_full_name"=>"Anwara Branch, Chittagong."),
		array("total_transection"=>7843,"branch_full_name"=>"Arshinagar Branch, Dhaka."),
		array("total_transection"=>8082,"branch_full_name"=>"Ashuganj Branch"),
		array("total_transection"=>8724,"branch_full_name"=>"Ashulia Branch"),
		array("total_transection"=>9718,"branch_full_name"=>"Bagerhat Branch"),
		array("total_transection"=>5980,"branch_full_name"=>"Banani Branch"),
		array("total_transection"=>8185,"branch_full_name"=>"Bandar Branch, Narayanganj"),
		array("total_transection"=>5058,"branch_full_name"=>"Barisal Branch"),
		array("total_transection"=>6854,"branch_full_name"=>"Bashundhara Branch"),
		array("total_transection"=>7498,"branch_full_name"=>"Bhawal Mirzapur Branch, Gazipur"),
		array("total_transection"=>5282,"branch_full_name"=>"Brahmanbaria Branch"),
		array("total_transection"=>6264,"branch_full_name"=>"Beani Bazar Branch"),
		array("total_transection"=>8387,"branch_full_name"=>"Belkuchi Branch"),
		array("total_transection"=>9275,"branch_full_name"=>"Benapole Branch"),
		array("total_transection"=>8415,"branch_full_name"=>"Bhuigar Branch, Narayanganj"),
		array("total_transection"=>5065,"branch_full_name"=>"Bhola Branch"),
		array("total_transection"=>6391,"branch_full_name"=>"Bajitpur Branch"),
		array("total_transection"=>7509,"branch_full_name"=>"Bandartila Branch"),
		array("total_transection"=>7287,"branch_full_name"=>"Banasree Branch, Dhaka."),
		array("total_transection"=>7515,"branch_full_name"=>"Baneshwar Branch"),
		array("total_transection"=>7095,"branch_full_name"=>"Board Bazar Branch"),
		array("total_transection"=>9491,"branch_full_name"=>"Boro Bazar Branch"),
		array("total_transection"=>7281,"branch_full_name"=>"Birol Bazar Branch"),
		array("total_transection"=>9656,"branch_full_name"=>"Chawk Bazar Branch"),
		array("total_transection"=>9229,"branch_full_name"=>"CCIS BRANCH"),
		array("total_transection"=>7489,"branch_full_name"=>"CDA Avenue Branch"),
		array("total_transection"=>5993,"branch_full_name"=>"Chandina Branch"),
		array("total_transection"=>9062,"branch_full_name"=>"Chapai Nawabganj Branch"),
		array("total_transection"=>5928,"branch_full_name"=>"Choumuhani Branch"),
		array("total_transection"=>9678,"branch_full_name"=>"Cherag Ali Branch, Gazipur"),
		array("total_transection"=>6130,"branch_full_name"=>"Chandra SME Krishi Branch"),
		array("total_transection"=>7516,"branch_full_name"=>"Chandraganj Branch"),
		array("total_transection"=>5985,"branch_full_name"=>"Comilla Branch"),
		array("total_transection"=>6194,"branch_full_name"=>"Coxs Bazar Branch"),
		array("total_transection"=>7738,"branch_full_name"=>"Companyganj Branch"),
		array("total_transection"=>8014,"branch_full_name"=>"Dania Branch"),
		array("total_transection"=>9606,"branch_full_name"=>"Dhamrai SME Krishi Branch"),
		array("total_transection"=>8585,"branch_full_name"=>"Dholaikhal Branch"),
		array("total_transection"=>7792,"branch_full_name"=>"Dinajpur Branch"),
		array("total_transection"=>6465,"branch_full_name"=>"Darus Salam Road Branch, Dhaka"),
		array("total_transection"=>9833,"branch_full_name"=>"Fatikchari Branch"),
		array("total_transection"=>5606,"branch_full_name"=>"Faridpur Branch"),
		array("total_transection"=>5351,"branch_full_name"=>"Feni Branch"),
		array("total_transection"=>5190,"branch_full_name"=>"Garibe Newaz Avenue Branch"),
		array("total_transection"=>5827,"branch_full_name"=>"Gabtoli Bagbari Branch"),
		array("total_transection"=>9241,"branch_full_name"=>"Ghorasal Branch"),
		array("total_transection"=>7189,"branch_full_name"=>"Goala Bazar Branch"),
		array("total_transection"=>8167,"branch_full_name"=>"Goalanda Branch"),
		array("total_transection"=>8570,"branch_full_name"=>"Gouripur Bazar Branch"),
		array("total_transection"=>8177,"branch_full_name"=>"Gulshan-Tejgaon Link Road Branch"),
		array("total_transection"=>9872,"branch_full_name"=>"Gazipur Chowrasta Branch"),
		array("total_transection"=>6185,"branch_full_name"=>"Habiganj Branch"),
		array("total_transection"=>9598,"branch_full_name"=>"Hasnabad Branch"),
		array("total_transection"=>5293,"branch_full_name"=>"Hathazari Branch"),
		array("total_transection"=>6689,"branch_full_name"=>"Isapura Bazar Branch"),
		array("total_transection"=>9793,"branch_full_name"=>"Jhalakathi Branch, Jhalakathi"),
		array("total_transection"=>7830,"branch_full_name"=>"Jamalpur Branch, Jamalpur"),
		array("total_transection"=>6922,"branch_full_name"=>"Joypurhat Branch"),
		array("total_transection"=>6223,"branch_full_name"=>"Juri Branch"),
		array("total_transection"=>5254,"branch_full_name"=>"Kachua Branch, Chandpur"),
		array("total_transection"=>9945,"branch_full_name"=>"Kaliganj SME Krishi Branch"),
		array("total_transection"=>9150,"branch_full_name"=>"Kashinathpur SME Krishi Branch"),
		array("total_transection"=>9223,"branch_full_name"=>"Keraniganj Branch"),
		array("total_transection"=>6265,"branch_full_name"=>"Khilgaon Branch"),
		array("total_transection"=>6381,"branch_full_name"=>"Konapara Branch"),
		array("total_transection"=>5282,"branch_full_name"=>"Konabari Branch"),
		array("total_transection"=>8029,"branch_full_name"=>"Kapasia Branch, Gazipur"),
		array("total_transection"=>9370,"branch_full_name"=>"Karatia Branch"),
		array("total_transection"=>5819,"branch_full_name"=>"Kushtia Branch"),
		array("total_transection"=>9426,"branch_full_name"=>"Lalmatia Branch"),
		array("total_transection"=>9854,"branch_full_name"=>"Local Office"),
		array("total_transection"=>5547,"branch_full_name"=>"Madhabdi Branch"),
		array("total_transection"=>9456,"branch_full_name"=>"Madhabpur Branch, Habiganj."),
		array("total_transection"=>9488,"branch_full_name"=>"Malibagh Branch"),
		array("total_transection"=>7042,"branch_full_name"=>"Manikgonj Branch"),
		array("total_transection"=>7444,"branch_full_name"=>"Moulvi Bazar Branch"),
		array("total_transection"=>8832,"branch_full_name"=>"Madam Bibir Hat Branch"),
		array("total_transection"=>6062,"branch_full_name"=>"Meghola Bazar Branch"),
		array("total_transection"=>8596,"branch_full_name"=>"Miah Bazar Branch"),
		array("total_transection"=>5963,"branch_full_name"=>"Mirpur Branch"),
		array("total_transection"=>5382,"branch_full_name"=>"Muktarpur Branch"),
		array("total_transection"=>8198,"branch_full_name"=>"Mohakhali Branch"),
		array("total_transection"=>5133,"branch_full_name"=>"Mohammadpur Branch"),
		array("total_transection"=>5842,"branch_full_name"=>"Mymensingh Branch"),
		array("total_transection"=>9893,"branch_full_name"=>"Mawna Branch,Gazipur"),
		array("total_transection"=>7442,"branch_full_name"=>"Moynamoti Branch, Comilla"),
		array("total_transection"=>8781,"branch_full_name"=>"Naogaon Branch"),
		array("total_transection"=>6906,"branch_full_name"=>"Narsingdi Branch"),
		array("total_transection"=>8865,"branch_full_name"=>"Nawabganj SME Krishi Branch"),
		array("total_transection"=>8922,"branch_full_name"=>"Naya Paltan Branch"),
		array("total_transection"=>7039,"branch_full_name"=>"North Brooke Hall Road Branch"),
		array("total_transection"=>5447,"branch_full_name"=>"Noju Miah Hat Branch"),
		array("total_transection"=>8699,"branch_full_name"=>"Netaiganj Branch"),
		array("total_transection"=>8174,"branch_full_name"=>"Panchaboti Branch"),
		array("total_transection"=>9645,"branch_full_name"=>"Pabna Branch"),
		array("total_transection"=>5571,"branch_full_name"=>"Panchdona Branch"),
		array("total_transection"=>5722,"branch_full_name"=>"Pallabi Branch"),

	);
	echo json_encode($data);


 	


 ?>