<?php 
	session_start();
	// Authentication Check
	if(!isset($_SESSION['id'])){
		header('location:../../../login.php');
		exit;
	}

 ?>

<?php 
	header('Content-Type: application/json');
	$data = array(
		array("avarage"=>669,"branch_name"=>"Aganagar Branch"),
		array("avarage"=>748,"branch_name"=>"Akhaura Branch"),
		array("avarage"=>864,"branch_name"=>"Alankar More Branch"),
		array("avarage"=>683,"branch_name"=>"Anwara Branch, Chittagong."),
		array("avarage"=>784,"branch_name"=>"Arshinagar Branch, Dhaka."),
		array("avarage"=>800,"branch_name"=>"Ashuganj Branch"),
		array("avarage"=>860,"branch_name"=>"Ashulia Branch"),
		array("avarage"=>600,"branch_name"=>"Bagerhat Branch"),
		array("avarage"=>911,"branch_name"=>"Banani Branch"),
		array("avarage"=>935,"branch_name"=>"Bandar Branch, Narayanganj"),
		array("avarage"=>762,"branch_name"=>"Barisal Branch"),
		array("avarage"=>854,"branch_name"=>"Bashundhara Branch"),
		array("avarage"=>844,"branch_name"=>"Bhawal Mirzapur Branch, Gazipur"),
		array("avarage"=>648,"branch_name"=>"Brahmanbaria Branch"),
		array("avarage"=>642,"branch_name"=>"Beani Bazar Branch"),
		array("avarage"=>872,"branch_name"=>"Belkuchi Branch"),
		array("avarage"=>697,"branch_name"=>"Benapole Branch"),
		array("avarage"=>559,"branch_name"=>"Bhuigar Branch, Narayanganj"),
		array("avarage"=>889,"branch_name"=>"Bhola Branch"),
		array("avarage"=>831,"branch_name"=>"Bajitpur Branch"),
		array("avarage"=>779,"branch_name"=>"Bandartila Branch"),
		array("avarage"=>980,"branch_name"=>"Banasree Branch, Dhaka."),
		array("avarage"=>689,"branch_name"=>"Baneshwar Branch"),
		array("avarage"=>553,"branch_name"=>"Board Bazar Branch"),
		array("avarage"=>732,"branch_name"=>"Boro Bazar Branch"),
		array("avarage"=>586,"branch_name"=>"Birol Bazar Branch"),
		array("avarage"=>812,"branch_name"=>"Chawk Bazar Branch"),
		array("avarage"=>667,"branch_name"=>"CCIS BRANCH"),
		array("avarage"=>730,"branch_name"=>"CDA Avenue Branch"),
		array("avarage"=>766,"branch_name"=>"Chandina Branch"),
		array("avarage"=>708,"branch_name"=>"Chapai Nawabganj Branch"),
		array("avarage"=>859,"branch_name"=>"Choumuhani Branch"),
		array("avarage"=>529,"branch_name"=>"Cherag Ali Branch, Gazipur"),
		array("avarage"=>980,"branch_name"=>"Chandra SME Krishi Branch"),
		array("avarage"=>618,"branch_name"=>"Chandraganj Branch"),
		array("avarage"=>638,"branch_name"=>"Comilla Branch"),
		array("avarage"=>709,"branch_name"=>"Coxs Bazar Branch"),
		array("avarage"=>703,"branch_name"=>"Companyganj Branch"),
		array("avarage"=>856,"branch_name"=>"Dania Branch"),
		array("avarage"=>775,"branch_name"=>"Dhamrai SME Krishi Branch"),
		array("avarage"=>681,"branch_name"=>"Dholaikhal Branch"),
		array("avarage"=>524,"branch_name"=>"Dinajpur Branch"),
		array("avarage"=>644,"branch_name"=>"Darus Salam Road Branch, Dhaka"),
		array("avarage"=>747,"branch_name"=>"Fatikchari Branch"),
		array("avarage"=>825,"branch_name"=>"Faridpur Branch"),
		array("avarage"=>603,"branch_name"=>"Feni Branch"),
		array("avarage"=>506,"branch_name"=>"Garibe Newaz Avenue Branch"),
		array("avarage"=>863,"branch_name"=>"Gabtoli Bagbari Branch"),
		array("avarage"=>529,"branch_name"=>"Ghorasal Branch"),
		array("avarage"=>698,"branch_name"=>"Goala Bazar Branch"),
		array("avarage"=>804,"branch_name"=>"Goalanda Branch"),
		array("avarage"=>679,"branch_name"=>"Gouripur Bazar Branch"),
		array("avarage"=>952,"branch_name"=>"Gulshan-Tejgaon Link Road Branch"),
		array("avarage"=>705,"branch_name"=>"Gazipur Chowrasta Branch"),
		array("avarage"=>847,"branch_name"=>"Habiganj Branch"),
		array("avarage"=>830,"branch_name"=>"Hasnabad Branch"),
		array("avarage"=>735,"branch_name"=>"Hathazari Branch"),
		array("avarage"=>685,"branch_name"=>"Isapura Bazar Branch"),
		array("avarage"=>625,"branch_name"=>"Jhalakathi Branch, Jhalakathi"),
		array("avarage"=>575,"branch_name"=>"Jamalpur Branch, Jamalpur"),
		array("avarage"=>661,"branch_name"=>"Joypurhat Branch"),
		array("avarage"=>697,"branch_name"=>"Juri Branch"),
		array("avarage"=>926,"branch_name"=>"Kachua Branch, Chandpur"),
		array("avarage"=>601,"branch_name"=>"Kaliganj SME Krishi Branch"),
		array("avarage"=>797,"branch_name"=>"Kashinathpur SME Krishi Branch"),
		array("avarage"=>516,"branch_name"=>"Keraniganj Branch"),
		array("avarage"=>950,"branch_name"=>"Khilgaon Branch"),
		array("avarage"=>743,"branch_name"=>"Konapara Branch"),
		array("avarage"=>567,"branch_name"=>"Konabari Branch"),
		array("avarage"=>535,"branch_name"=>"Kapasia Branch, Gazipur"),
		array("avarage"=>746,"branch_name"=>"Karatia Branch"),
		array("avarage"=>588,"branch_name"=>"Kushtia Branch"),
		array("avarage"=>647,"branch_name"=>"Lalmatia Branch"),
		array("avarage"=>967,"branch_name"=>"Local Office"),
		array("avarage"=>665,"branch_name"=>"Madhabdi Branch"),
		array("avarage"=>541,"branch_name"=>"Madhabpur Branch, Habiganj."),
		array("avarage"=>843,"branch_name"=>"Malibagh Branch"),
		array("avarage"=>835,"branch_name"=>"Manikgonj Branch"),
		array("avarage"=>732,"branch_name"=>"Moulvi Bazar Branch"),
		array("avarage"=>995,"branch_name"=>"Madam Bibir Hat Branch"),
		array("avarage"=>688,"branch_name"=>"Meghola Bazar Branch"),
		array("avarage"=>804,"branch_name"=>"Miah Bazar Branch"),
		array("avarage"=>796,"branch_name"=>"Mirpur Branch"),
		array("avarage"=>762,"branch_name"=>"Muktarpur Branch"),
		array("avarage"=>566,"branch_name"=>"Mohakhali Branch"),
		array("avarage"=>888,"branch_name"=>"Mohammadpur Branch"),
		array("avarage"=>586,"branch_name"=>"Mymensingh Branch"),
		array("avarage"=>700,"branch_name"=>"Mawna Branch,Gazipur"),
		array("avarage"=>711,"branch_name"=>"Moynamoti Branch, Comilla"),
		array("avarage"=>692,"branch_name"=>"Naogaon Branch"),
		array("avarage"=>604,"branch_name"=>"Narsingdi Branch"),
		array("avarage"=>502,"branch_name"=>"Nawabganj SME Krishi Branch"),
		array("avarage"=>810,"branch_name"=>"Naya Paltan Branch"),
		array("avarage"=>616,"branch_name"=>"North Brooke Hall Road Branch"),
		array("avarage"=>951,"branch_name"=>"Noju Miah Hat Branch"),
		array("avarage"=>750,"branch_name"=>"Netaiganj Branch"),
		array("avarage"=>712,"branch_name"=>"Panchaboti Branch"),
		array("avarage"=>987,"branch_name"=>"Pabna Branch"),
		array("avarage"=>890,"branch_name"=>"Panchdona Branch"),

	);
	echo json_encode($data);

 ?>
